version: '3.9'

networks:
    jp_network:
        external: true

services:
    backend:
        build:
            context: ../
            dockerfile: ./docker/Dockerfile
        env_file:
            - ../.env
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://backend:7000/health-check']
            interval: 30s
            retries: 5
            timeout: 10s
        networks:
            - jp_network
        ports:
            - '7000:7000'
        restart: unless-stopped
