export const MESSAGES = {
    ADDED_TO_CART_SUCCESSFULLY: 'Added to cart successfully.',
    CART_LOADED_SUCCESSFULLY: 'Cart loaded successfully.',
    DOCUMENT_NOT_FOUND: 'Data not found.',
    DUPLICATE_DATABASE_ENTRY: 'Duplicate database entry.',
    EMAIL_ALREADY_IN_USE: 'Email already in use.',
    EMAIL_VERIFICATION_SUBJECT: 'Email Verification',
    EMAIL_VERIFICATION_TEXT: 'Verify your email by clicking the following link: ',
    EMAIL_VERIFIED_SUCCESSFULLY: 'Email verified successfully.',
    INVALID_CREDENTIALS: 'Invalid credentials.',
    INVALID_REQUEST: 'Invalid request.',
    INVALID_TOKEN: 'Invalid or expired token.',
    LOGIN_SUCCESSFUL: 'Login successful.',
    NOT_AUTHORIZED: 'Not authorized.',
    NO_TOKENS_PROVIDED: 'No token provided.',
    NOT_LOGGED_IN: 'Not logged in.',
    ORDER_HISTORY_LOADED_SUCCESSFULLY: 'Order history loaded successfully.',
    PASSWORD_RESET_EMAIL_SENT: 'Password reset email sent.',
    PASSWORD_RESET_SUBJECT: 'Password Reset',
    PASSWORD_RESET_SUCCESS: 'Password reset successfully.',
    PASSWORD_RESET_TEXT: 'Reset your password by clicking the following link: ',
    PRODUCT_CREATED: 'Product created successfully.',
    PRODUCT_DELETED: 'Product deleted successfully.',
    PRODUCTS_LOADED: 'Products loaded successfully.',
    PRODUCT_NOT_FOUND: 'Product not found.',
    PRODUCT_UPDATED: 'Product updated successfully.',
    REMOVED_FROM_CART_SUCCESSFULLY: 'Removed from cart successfully.',
    TOKEN_REFRESHED: 'Token refreshed successfully.',
    USER_LOGGED_OUT_SUCCESSFULLY: 'User logged out successfully.',
    USER_NOT_FOUND: 'User not found.',
    USER_REGISTERED_VERIFICATION_EMAIL_SENT: 'User registered. Verification email sent.',
    VERIFICATION_EMAIL_SENT: 'Verification email sent.',
};
