name: CI.

on:
  push:
    branches: ['main']
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

env:
  HUSKY: 0

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: read
    steps:
      - name: Checkout code.
        uses: actions/checkout@v4

      - name: Setup node.
        uses: actions/setup-node@v4
        with:
          node-version: '20.12.0'

      - name: Install dependencies.
        run: npm ci

      - name: Run tests.
        run: npm test && npx codecov

      - name: Upload coverage reports to Codecov.
        uses: codecov/codecov-action@v4.5.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  release:
    runs-on: ubuntu-latest
    needs: build-push
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout code.
        uses: actions/checkout@v4

      - name: Setup node.
        uses: actions/setup-node@v4
        with:
          node-version: '20.12.0'

      - name: Install dependencies.
        run: npm ci

      - name: Create release.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release